export const players = {
  "players": [
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "C Lynn",
      "event_id": 2989,
      "price": 95000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Chris Lynn",
      "player_id": 855,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "N Rana",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Nitish Rana",
      "player_id": 1011,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "R Uthappa",
      "event_id": 2989,
      "price": 95000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Robin Uthappa",
      "player_id": 1062,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "I Jaggi",
      "event_id": 2989,
      "price": 70000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Ishank Jaggi",
      "player_id": 8385,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "Rinku",
      "event_id": 2989,
      "price": 65000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Rinku Singh",
      "player_id": 9275,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "S Gill",
      "event_id": 2989,
      "price": 65000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Shubman Gill",
      "player_id": 11033,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "A Wankhade",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Apoorv Wankhade",
      "player_id": 11357,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 1,
      "player_img": null,
      "short_name": "D Karthik",
      "event_id": 2989,
      "price": 90000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Dinesh Karthik",
      "player_id": 870,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "A Russell",
      "event_id": 2989,
      "price": 100000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Andre Russell",
      "player_id": 549,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "S Narine",
      "event_id": 2989,
      "price": 100000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Sunil Narine",
      "player_id": 1107,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "C Delport",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Cameron Delport",
      "player_id": 9180,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "Kuldeep",
      "event_id": 2989,
      "price": 85000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Kuldeep Yadav",
      "player_id": 954,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "M Johnson",
      "event_id": 2989,
      "price": 90000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Mitchell Johnson",
      "player_id": 972,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "P Chawla",
      "event_id": 2989,
      "price": 85000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Piyush Chawla",
      "player_id": 1014,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "Vinay",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Vinay Kumar",
      "player_id": 1146,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "J Searles   ",
      "event_id": 2989,
      "price": 75000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Javon Searles   ",
      "player_id": 5497,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "T Curran",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Tom Curran",
      "player_id": 9243,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "S Mavi",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Shivam Mavi",
      "player_id": 11458,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "P Krishna",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 77,
      "full_name": "Prasidh Krishna",
      "player_id": 11562,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "Rohit",
      "event_id": 2989,
      "price": 105000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Rohit Sharma",
      "player_id": 258,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "JP Duminy",
      "event_id": 2989,
      "price": 90000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Jean-Paul Duminy",
      "player_id": 621,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "E Lewis",
      "event_id": 2989,
      "price": 95000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Evin Lewis",
      "player_id": 764,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "S Lad",
      "event_id": 2989,
      "price": 65000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Siddhesh Lad",
      "player_id": 1098,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "S Tiwary",
      "event_id": 2989,
      "price": 75000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Saurabh Tiwary",
      "player_id": 1122,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "Suryakumar",
      "event_id": 2989,
      "price": 75000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Suryakumar Yadav",
      "player_id": 1125,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 4,
      "player_img": null,
      "short_name": "S Lumba",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Sharad Lumba",
      "player_id": 11473,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 1,
      "player_img": null,
      "short_name": "A Tare",
      "event_id": 2989,
      "price": 75000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Aditya Tare",
      "player_id": 828,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 1,
      "player_img": null,
      "short_name": "I Kishan",
      "event_id": 2989,
      "price": 70000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Ishan Kishan",
      "player_id": 894,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "Hardik",
      "event_id": 2989,
      "price": 95000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Hardik Pandya",
      "player_id": 237,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "B Cutting",
      "event_id": 2989,
      "price": 85000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Ben Cutting",
      "player_id": 837,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "Krunal",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Krunal Pandya",
      "player_id": 939,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "K Pollard",
      "event_id": 2989,
      "price": 90000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Kieron Pollard",
      "player_id": 945,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "T Dhillon",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Tajinder Dhillon",
      "player_id": 11479,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 2,
      "player_img": null,
      "short_name": "AS Roy",
      "event_id": 2989,
      "price": 65000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Anukul Sudhakar Roy",
      "player_id": 11480,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "Mustafizur",
      "event_id": 2989,
      "price": 95000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Mustafizur Rahman",
      "player_id": 114,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "J Bumrah",
      "event_id": 2989,
      "price": 100000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Jasprit Bumrah",
      "player_id": 240,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "A Milne",
      "event_id": 2989,
      "price": 85000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Adam Milne",
      "player_id": 501,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "M M'naghan",
      "event_id": 2989,
      "price": 90000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Mitchell McClenaghan",
      "player_id": 528,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "P Sangwan",
      "event_id": 2989,
      "price": 75000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Pradeep Sangwan",
      "player_id": 1035,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "R Chahar",
      "event_id": 2989,
      "price": 65000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Rahul Chahar",
      "player_id": 9305,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "A Dananjaya",
      "event_id": 2989,
      "price": 80000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Akila Dananjaya",
      "player_id": 9963,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "MD Nidheesh",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "MD Nidheesh",
      "player_id": 11334,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "M Markande",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Mayank Markande",
      "player_id": 11474,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    },
    {
      "profile": null,
      "skill_id": 3,
      "player_img": null,
      "short_name": "Mohsin Khan",
      "event_id": 2989,
      "price": 60000,
      "not_available": 0,
      "team_id": 80,
      "full_name": "Mohsin Khan",
      "player_id": 11482,
      "overseas": 0,
      "uncapped": 0,
      "tournament_id": 324,
      "opt_skill_id": 0
    }
  ]
};
